# Generated by Django 4.0.3 on 2022-04-04 16:19

import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('titles', models.TextField()),
                ('text', ckeditor.fields.RichTextField()),
                ('personal_informations', models.TextField()),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('university', models.CharField(max_length=200)),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Expericence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('how_learned', models.CharField(choices=[('SelfStudy', 'SelfStudy'), ('By Master', 'By Master')], max_length=12)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Skills_Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('percentage', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('color', models.CharField(choices=[('bg-primary', 'WebTheme'), ('bg-danger', 'Red'), ('bg-success', 'Green'), ('bg-warning', 'Yellow'), ('bg-info', 'Blue')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Workship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.URLField(max_length=530)),
                ('screen_shot', models.ImageField(blank=True, default='static/freelancer-portfolio-template.jpg', null=True, upload_to='screen_shots/')),
                ('short_description', models.CharField(max_length=250)),
            ],
        ),
    ]
