# Generated by Django 4.0.3 on 2022-04-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Informations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshipSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
            ],
        ),
    ]
