# Generated by Django 4.0.3 on 2022-04-04 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Informations', '0002_workshipsubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='workship',
            name='Workship_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Informations.workshipsubject'),
        ),
    ]
