# Generated by Django 4.0.3 on 2022-04-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Informations', '0003_workship_workship_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('subject', models.CharField(max_length=350)),
                ('email', models.EmailField(max_length=254)),
                ('text', models.TextField()),
                ('read_or_not', models.BooleanField()),
            ],
        ),
    ]
