# Generated by Django 4.0.3 on 2022-04-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Informations', '0005_alter_contactme_read_or_not'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='CV',
            field=models.URLField(blank=True, null=True),
        ),
    ]
